In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


In [4]:
mnist = tf.keras.datasets.mnist #handwritten digits dataset

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.24885319, -0.5108828 ,  0.6453566 ,  0.74144405,  0.14026035,
         0.4022149 , -0.30897653, -0.649443  ,  0.2936335 ,  0.44712102]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.06394802, 0.04920725, 0.15637866, 0.17215028, 0.09436631,
        0.12262596, 0.06021656, 0.04284037, 0.11000846, 0.12825812]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [24]:
loss_fn(y_train[:1], predictions).numpy() #This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

2.0986166

In [25]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [33]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0180 - accuracy: 0.9937
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0164 - accuracy: 0.9941
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0159 - accuracy: 0.9945
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0141 - accuracy: 0.9951
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0160 - accuracy: 0.9944


In [40]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0997 - accuracy: 0.9823 - 1s/epoch - 4ms/step


[0.09966346621513367, 0.9822999835014343]

In [42]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [44]:
probability_model(x_test[:5]).numpy()

array([[1.2914581e-22, 7.9120795e-21, 9.1407604e-19, 4.7192830e-11,
        3.4692667e-28, 3.8509975e-21, 1.5650734e-31, 1.0000000e+00,
        4.3521027e-19, 1.0143697e-14],
       [3.4962650e-27, 2.5472337e-17, 1.0000000e+00, 4.1934950e-19,
        0.0000000e+00, 1.5905959e-20, 7.9914149e-25, 7.1349807e-34,
        1.3786916e-18, 0.0000000e+00],
       [3.5778831e-17, 9.9999976e-01, 7.2888575e-08, 5.2819836e-13,
        1.3900237e-11, 2.3761410e-16, 5.4359199e-12, 1.2361525e-07,
        1.8583759e-08, 4.8773105e-16],
       [1.0000000e+00, 1.2606153e-26, 1.0857002e-09, 2.3888398e-11,
        2.4472223e-17, 2.8703578e-13, 3.3795048e-12, 2.9029237e-10,
        3.7258789e-17, 3.2071604e-08],
       [1.3806579e-13, 2.2596429e-29, 4.0320576e-16, 1.0527197e-17,
        9.9984145e-01, 2.1116449e-18, 6.2285329e-16, 4.0309275e-12,
        6.3691610e-17, 1.5854578e-04]], dtype=float32)